-- WITHOUT ; AT THE END OF THE SQL STATEMENT !
INSERT INTO DISPATCHER.TGPSDATA (
    DDATA,
    NTIME,
    CID,
    NNUM,
    CLATITUDE,
    CNS,
    CLONGTITUDE,
    CEW,
    CCURSE,
    CSPEED,
    CFUEL,
    CDATAVALID,
    CNAPR,
    CBAT,
    CTEMPER,
    CZAJ,
    CSATEL,
    CPROBEG,
    CIN0,
    CIN1,
    CIN2,
    CIN3,
    CIN4,
    CIN5,
    CIN6,
    CIN7
) VALUES (
    :1,  -- DDATA,
    :2,  -- NTIME,
    :3,  -- CID,
    :4,  -- NNUM,
    :5,  -- CLATITUDE,
    :6,  -- CNS,
    :7,  -- CLONGTITUDE,
    :8,  -- CEW,
    :9,  -- CCURSE,
    :10,  -- CSPEED,
    :11,  -- CFUEL,
    :12,  -- CDATAVALID,
    :13,  -- CNAPR,
    :14,  -- CBAT,
    :15,  -- CTEMPER,
    :16,  -- CZAJ,
    :17,  -- CSATEL,
    :18,  -- CPROBEG,
    :19,  -- CIN0,
    :20,  -- CIN1,
    :21,  -- CIN2,
    :22,  -- CIN3,
    :23,  -- CIN4,
    :24,  -- CIN5,
    :25,  -- CIN6,
    :26  -- CIN7,
)
